define(['./queueservicex',
        './queueclassservicex',
        './windowservice',
        './userservice',
        './socketservice',
        './indexedDbService',
        './externalSysService',
        './ticketService',
        './dictService'],function(){});