require.config({
	baseUrl:'scripts',
	paths:{
		'jquery':'../bower_components/jquery/dist/jquery',
		'angular':'../bower_components/angular/angular',
		'angular-route':'../bower_components/angular-route/angular-route',
		'angular-md5':'../bower_components/angular-md5/angular-md5',
		'angular-bootstrap':'../bower_components/angular-bootstrap/ui-bootstrap',
		'bootstrap':'../bower_components/bootstrap/dist/js/bootstrap',
		'bootstrap-toggle':'../bower_components/bootstrap-toggle/js/bootstrap2-toggle',
		'socketio':'/socket.io/socket.io',
		'domReady':'lib/domReady',
		'boot':'boot',
		'appx':'appx',
		'router':'router'
	},
	shim:{
		'bootstrap':{
			deps:['jquery'],
			exports:'bootstrap'
		},
		'bootstrap-toggle':{
			deps:['jquery','bootstrap'],
			exports:'bootstrap-toggle'
		},
		'angular':{
			exports:'angular'
		},
		'angular-route':{
			deps:['angular'],
			exports:'angular-route'
		},
		'angular-md5':{
			deps:['angular'],
			exports:'angular-md5'	
		},
		'angular-bootstrap':{
			deps:['angular'],
			exports:'angular-bootstrap'	
		},
	},
	deps:['boot']
});